### PR TITLE
Application gateway: enable HTTP2 traffic

### PR DESCRIPTION
**Pull request by Enjeej**
Added support for enabling/disabling HTTP2 traffic support on the application gateway

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@Enjeej could you take a look and sing CLA please?

**Comment by Enjeej** [comment]
@hovsepm about the CLA, I just saw it and already wrote an email to my employer to get formal approval

**Comment by Enjeej** [comment]
@lenala I've removed the casts

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Pull request merged**
