### PR TITLE
Fix FilterAtTenantLevel() for ActivityLogsImpl

### PR DESCRIPTION
**Pull request by wanxms**
An 'and' is missing in filterString.

### CODE REVIEW

**Comment by wanxms** [comment]
Not sure why these BVTs cannot pass. Please help to take a look.

**Comment by weidongxu-microsoft** [comment]
@wanxms 
The change on query requires re-run of related live tests.

Do you have any case that could have different result before/after the fix? I can put it into test for you.

**Comment by wanxms** [comment]
@weidongxu-microsoft nope, I just happened to find the query parameter is obviously not correct when debugging another issue. I have not tested the fix.

Btw, the issue I hit is some logs can not be retrieved by the library.
An example is for VirtualMachine, when someone/services restart the VM inside the VM, the following log can be found on Azure Portal but not returned by this library.
`
{
    "channels": "Admin, Operation",
    "correlationId": "a45bdd75-03e9-4a99-854b-0d2b2753bf3a",
    "description": "",
    "eventDataId": "c06783c1-27d2-4b4f-a5ff-c94d30589a95",
    "eventName": {
        "value": "",
        "localizedValue": ""
    },
    "category": {
        "value": "ResourceHealth",
        "localizedValue": "Resource Health"
    },
    "eventTimestamp": "2020-03-31T03:15:01.061Z",
    "id": "/subscriptions/33922553-c28a-4d50-ac93-a5c682692168/resourceGroups/xscnvm-vmactivitylog/providers/Microsoft.Compute/virtualMachines/vmactivitylog/events/c06783c1-27d2-4b4f-a5ff-c94d30589a95/ticks/637212213010610000",
    "level": "Informational",
    "operationId": "",
    "operationName": {
        "value": "Microsoft.Resourcehealth/healthevent/Resolved/action",
        "localizedValue": "Health Event Resolved"
    },
    "resourceGroupName": "xscnvm-vmactivitylog",
    "resourceProviderName": {
        "value": "Microsoft.Resourcehealth/healthevent/action",
        "localizedValue": "Microsoft.Resourcehealth/healthevent/action"
    },
    "resourceType": {
        "value": "MICROSOFT.COMPUTE/VIRTUALMACHINES",
        "localizedValue": "MICROSOFT.COMPUTE/VIRTUALMACHINES"
    },
    "resourceId": "/subscriptions/33922553-c28a-4d50-ac93-a5c682692168/resourceGroups/xscnvm-vmactivitylog/providers/Microsoft.Compute/virtualMachines/vmactivitylog",
    "status": {
        "value": "Resolved",
        "localizedValue": "Resolved"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2020-03-31T03:17:46.5568339Z",
    "subscriptionId": "33922553-c28a-4d50-ac93-a5c682692168",
    "tenantId": "",
    "properties": {
        "title": "Unknown",
        "details": "Unknown",
        "currentHealthStatus": "Available",
        "previousHealthStatus": "Unavailable",
        "type": "Unknown",
        "cause": "Unknown"
    },
    "relatedEvents": []
}
`
For now, I can mitigate this issue by using some reflect hacks, adding 'and eventChannels eq 'Admin, Operation'' to the query and use 2017-03-01-preview as the API version.
Maybe you guys have more context on how to fix it?

**Comment by weidongxu-microsoft** [comment]
@wanxms

Thanks. I will try this case. BTW, does apiVersion `2017-03-01-preview` matter in this case? The latest published spec only being 2015-04-01...

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/stable/2015-04-01/tenantActivityLogs_API.json#L44

**Comment by wanxms** [comment]
@weidongxu-microsoft Looks like the api-version matters. It doesn't work if I only add 'and eventChannels eq 'Admin, Operation'' to the query.

**Pull request merged**
