### PR TITLE
Create the resource group if it does not exist on BeginCreate().

### LINKED ISSUE #127: BeginCreate does not work with New resource groups
If you create a deployment and use `BeginCreate()` when you have specified `WithNewResourceGroup`, it always seems to immediately return an error that the resource group could not be found (and indeed on inspection in the portal, the RG has indeed not been created). If the resource group already exists, the deployment proceeds correctly.

If you use `Create()` instead, the resource group is correctly created before the deployment is applied (even if that deployment then fails).

### PR DESCRIPTION
**Pull request by isaacabraham**
Fixes #127.

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@isaacabraham your PR is missing test records. I've created a pull request with the necessary files to your repo https://github.com/isaacabraham/azure-libraries-for-net/pull/1 . When you will merge it this PR will pass CI builds. 
Thanks for your contribution!

**Comment by isaacabraham** [comment]
@hovsepm cool, merged in - thanks. I have no clue what those test records are or how they work, so wouldn't have easily been able to do that myself. Thanks!

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Pull request merged**
