### PR TITLE
[Fix]: Adding StorageAccountTypes::StandardSSD_LRS, [Samples]: Storage network rules & compute SKU

### PR DESCRIPTION
**Pull request by anuchandy**
Adding `StandardSSD_LRS` enum value to `StorageAccountTypes` in this [commit](https://github.com/Azure/azure-libraries-for-net/commit/a59c1b979e4e827572729647b51238f3832ffd40). Opened an [issue](https://github.com/Azure/azure-rest-api-specs/issues/2343)  in rest api spec. For now this need to be manually patched otherwise deserialization of the values *will fail* and clients will start seeing exceptions.

### CODE REVIEW

**Comment by samyak4680** [comment]
Hi,

I am using ultra SSD disks  (available in the preview mode), but getting the following output while getting the vm details in rest api:

->
Deserializer is not able to find UltraSSD_LRS as valid enum in <enum 'StorageAccountTypes'>
<-

Can you please get the UltraSSD_LRS enum added to the StorageAccountTypes to fix this issue?

**Comment by yaohaizh** [comment]
@samyak4680 what is your fluent lib version?

**Comment by samyak4680** [comment]
Apologies for not sharing the SDK type. I am using the Python SDK. Can you please check on it.

**Comment by yaohaizh** [comment]
@samyak4680, you can log an issue aganist this repo: https://github.com/Azure/azure-sdk-for-python

**Pull request merged**
