### PR TITLE
ApplicationGateway: Extract and set the tier when the size is being set.

### PR DESCRIPTION
**Pull request by Enjeej**
When the size of an Application Gateway is being set the tier can be extracted and set.

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by Enjeej** [comment]
@hovsepm I think all check have past:  _"All checks have passed"_

**Comment by hovsepm** [comment]
@lenala could you review this PR?

**Comment by Enjeej** [comment]
@lenala could you please have a look at this PR. I've been so foolish to add this feature in the master branch of my fork. Now I cannot create any another PR for different features without the feature in this PR also being included.

**Comment by Enjeej** [comment]
@lenala Thank you!

**Pull request merged**
