### PR TITLE
Support Region.SwedenCentral

### PR DESCRIPTION
**Pull request by andtii**
Adds the missing region support for SwedenCentral

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
@andtii 
Thanks for your contribution.
The codebase is in maintenance mode, hence we are not likely to release new version in near future.

User is encouraged to use new SDK here https://aka.ms/azsdk/dotnet/mgmt

**Comment by qub1n** [comment]
@weidongxu-microsoft 

Are you going to support Azure Qatar region as well?

https://www.datacenterdynamics.com/en/news/microsofts-qatar-azure-region-to-launch-in-two-weeks/

**Comment by weidongxu-microsoft** [comment]
Found it.

```json
{
    "id" : "/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/locations/qatarcentral",
    "name" : "qatarcentral",
    "type" : "Region",
    "displayName" : "Qatar Central",
    "regionalDisplayName" : "(Middle East) Qatar Central",
    "metadata" : {
      "regionType" : "Physical",
      "regionCategory" : "Recommended",
      "geographyGroup" : "Middle East",
      "longitude" : "51.439327",
      "latitude" : "25.551462",
      "physicalLocation" : "Doha",
      "pairedRegion" : [ {
        "name" : "westeurope",
        "id" : "/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/locations/westeurope"
      } ]
    }
  }
```

Will test the region on Azure, if works fine, we will add it to https://aka.ms/azsdk/dotnet/mgmt

**Comment by weidongxu-microsoft** [comment]
PR for qatar https://github.com/Azure/azure-sdk-for-java/pull/30503

**Comment by qub1n** [comment]
I see the Qatar was added to Java, do we need it in .NET as well?

**Comment by weidongxu-microsoft** [comment]
@qub1n 

The .NET SDK here is to be deprecated (I will try add one here, but unsure of next release date).

@fengzhou-msft on track2 https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/AzureLocation.cs

**Comment by weidongxu-microsoft** [comment]
@qub1n

If you need Qatar in new SDK, you can create an issue here https://github.com/Azure/azure-sdk-for-net/issues

**Pull request merged**
