### PR TITLE
Binding HostName to Deployment slot uses name incorrectly.

### PR DESCRIPTION
**Pull request by steveofficer**
When binding a hostname to a webapp deployment slot, the deployment slot name was not being sent correctly as a part of the request to Azure.

The request was using the fully qualified slot name rather than just the actual name of the slot. This then resulted in Azure returning an error stating that the resource could not be found.

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@jianghaolu  could you take a look to the PR?

**Comment by praries880** [comment]
@jianghaolu Can you take a look at this PR?

**Comment by praries880** [comment]
@azuresdkci test this please

**Comment by praries880** [comment]
@steveofficer can you kindly sign the CLA in the thread?

I had to make a no-op change to your branch to kick off a new CI.

**Comment by praries880** [comment]
@azuresdkci test this please

**Comment by praries880** [comment]
@azuresdkci re-test this please

**Pull request merged**
